version: '3.7'

services:
  rdt-client:
    image: rogerfar/rdtclient:latest
    container_name: debrid
    restart: unless-stopped
    networks:
      - web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /media/data/Media/:/data/downloads
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.http.routers.debrid.entrypoints=http"
      - "traefik.http.routers.debrid.rule=Host(`debrid.snackk-media.com`)"
      - "traefik.http.middlewares.debrid-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.debrid-https-redirect.redirectscheme.permanent=true"
      - "traefik.http.routers.debrid.middlewares=debrid-https-redirect"
      - "traefik.http.services.debrid.loadbalancer.server.port=6500"

      - "traefik.http.routers.debrid-secure.entrypoints=https"
      - "traefik.http.routers.debrid-secure.rule=Host(`debrid.snackk-media.com`)"
      - "traefik.http.routers.debrid-secure.tls=true"
      - "traefik.http.routers.debrid-secure.tls.certresolver=ssl-cert"
      - "traefik.http.routers.debrid-secure.service=debrid"

networks:
  web:
    external: true
